### ISSUE TITLE
http://syzygy-tables.info should redirect to https://syzygy-tables.info

### ISSUE THREAD

**Issue by lgarron** [niklasf/syzygy-tables.info#1]
It's not good practice to rely on the preload list alone.

**Comment by niklasf** [comment]
Thank you for the hint, I wasn't sure what the best practise is, here. Should I completely redirect every single page including the API (like I did just now) or just the user interface?

**Comment by lgarron** [comment]
It's safest and simplest to redirect everything. As soon as the main page is redirected, HSTS will apply to all the subresources, so you don't pay a redirect cost for them.

The current state of things looks good!
