### ISSUE TITLE
Display the DTZ mainline

### ISSUE THREAD

**Issue by niklasf** [niklasf/syzygy-tables.info#2]
Consider displaying the full DTZ mainline for winning and losing positions. Maybe offer a PGN download.

**Comment by mcostalba** [comment]
Just want to report that we mention this feature at the bottom of https://github.com/official-stockfish/Stockfish/pull/731

Congratulations for the site https://syzygy-tables.info/ really awesome :-)

**Comment by niklasf** [comment]
Hi, thanks a lot.

The DTZ mainline is not yet shown in the UI, but it can be downloaded as PGN with the link below the move list. The API is simply: https://syzygy-tables.info/syzygy-vs-syzygy/anyfilename.pgn?fen=4k3/2Q5/8/8/8/8/8/4K3_b_-_-_0_1

But let me point out that it's not a good idea to use this as verification for Stockfish, because it is based on my Python port of Stockfish's own probing code :D

**Comment by mcostalba** [comment]
Great!

Actually we will update the syzygy code from current one (original from
Ronald de Man) to my C++ port that is much better documented and clear (at
least for me):

https://github.com/official-stockfish/Stockfish/pull/731

Before this, we are extensively and deeply testing the new code for no
regression and to ensure that is 100% functional equivalent to the original
one (and as of today, after some very deep tests, we can say it is).
