### ISSUE TITLE
add DTM50 to Syzygy, please

### ISSUE THREAD

**Issue by andrew-buchanan** [niklasf/syzygy-tables.info#266]
Hi, it naively seems to me that DTM50 promised to be the answer to resolving the tension between DTM & DTZ50. There was lots of discussion by kronsteen, which syzygy commented on about 10 years ago, and it looked as if it was really moving forwards.  Is there any chance that it can be supported by syzygy, please?

The use case is "retro studies" - endgame studies that engage 50M rule. Even having something for 5 pieces would be great, to solve some non-trivial problems, and get an impression of what the impact of DTM50 might be when scaled up.

**Comment by niklasf** [comment]
Sorry, major projects like that are out of scope for this website, but I am happy to serve the data if any format emerges.
