### ISSUE TITLE
Is rounding still needed?

### ISSUE THREAD

**Issue by andrew-buchanan** [niklasf/syzygy-tables.info#267]
Hi I constructing studies that engage with 50M rule. 

I normally try to make them as edgy as possible, so they are not sitting safely in the middle of DTZ certainty. This rounding business is all a bit wearing. I don't suppose there is any chance that since storage is cheaper than it was before, you might be able to dispense with the rounding. 

Even for values less than 7, it would be good.

Thanks,
Andrew

**Comment by niklasf** [comment]
I published an experimental 5 piece tablebase without rounding at https://no-rounding.syzygy-tables.info/. Its size is 1007 MiB compared to 939 MiB, so the savings appear pretty minor at this piece count.

Higher piece counts also seem doable. But I hesistate to publish any data or tables that differ from the "official" Syzygy.

**Comment by niklasf** [comment]
Updated the main site as follows:

> The tables up to 5 pieces *on this site* have been generated with [a patch to avoid rounding for 100 ≥ n ≥ 1](https://github.com/niklasf/tb/commit/9f1056429ad379eff52e748dc2783ea750671730).

6 piece tables are in progress.

**Comment by niklasf** [comment]
Done also for 6 pieces.

Almost all tables are affected, so the resources required for going all the way to 7 pieces are hard to justify.
