### ISSUE TITLE
DTM for 6 units

### ISSUE THREAD

**Issue by andrew-buchanan** [niklasf/syzygy-tables.info#268]
Is there a chance to make DTM available for 6 units please?

Thanks,
Andrew

**Comment by andrew-buchanan** [comment]
Very often, a 7-man position of interest is tense and involves 50M, so DTZ is necessary and behaves well. But a lot of tension is lost when a unit is captured, and DTZ may no longer be needed or sensible (e.g. it may decide to sacrifice a superfluous unit). Therefore it would be very useful to have DTM for 6 units, and the bulk is not that great.

**Comment by niklasf** [comment]
Unfortunately I don't believe there is any suitable 6 piece DTM implementation. For instance, Nalimov has unacceptable licensing conditions.
