### ISSUE TITLE
Show DTM of current position

### ISSUE THREAD

**Issue by andrew-buchanan** [niklasf/syzygy-tables.info#270]
Hi,

Easy one this time, please. 

For up to 5 pieces you show the DTZ & DTM for each move option. But at the top you only show the DTZ for the current position, not the DTM. To find out the current DTM I have to retract a move, which is a bit odd. Can you add the DTM at the top please.

Thanks,
Andrew

**Comment by niklasf** [comment]
Makes sense. Added.
