### ISSUE TITLE
Key bindings for more convenient interface

### ISSUE THREAD

**Issue by elexunix** [niklasf/syzygy-tables.info#358]
Hello! The database is great!
I wonder if it is possible to make, say, the space key be used to automatically play the best move out of the list. I guess it is relatively easy, since it just requires adding a few lines to the front-end. This will make it even more pleasuring to use, since it is an often usecase -- to look through the optimal play line, currently it requires clicking on a move each time

**Comment by niklasf** [comment]
Good idea. Added the space shortcut.
