### ISSUE TITLE
Error 429: Too many requests

### ISSUE THREAD

**Issue by kudhru** [niklasf/syzygy-tables.info#4]
Hi

I am trying to generate the `wdl` for around 20000 FENs. I am hitting the below API without any time delay and therefore getting the '429: too many requests' error.

https://syzygy-tables.info/apidoc?fen=8/8/p4pr1/1k6/K7/8/8/8%20w%20-%20-%200%201

Does anyone what should be the time delay between two requests so that I don't receive the 429 error? Or what are the maximum number of requests allowed per min or per hour?

**Comment by niklasf** [comment]
Hi @kudhru, I don't know the delay exactly at the top of my head, but it's probably going to take a long time for 20000 positions. If you can share the 20000 FENs I can query the tablebases for you offline, or you could download a copy of the tablebases and query them offline yourself.
