### ISSUE TITLE
Make the lock side to move button clearer

### ISSUE THREAD

**Issue by Alayan-stk-2** [niklasf/syzygy-tables.info#7]
When looking at various TB positions, I often think "what if this piece was on that square instead of this square". But if moving the piece such a way happens to match a legal chess move, the side to move will be automatically changed, which is neat when trying to play a sequence of moves but is an hindrance in my situation.

Thus, some checkbox to be able to enable/disable at will this side to move behavior would be much appreciated.

**Comment by niklasf** [comment]
If I understand you correctly this exists: Edit mode, rightmost button below the board.

**Comment by Alayan-stk-2** [comment]
Funnily enough, I found about it 1 minute ago when fiddling with options to see if something else was possible (I'd like to get a random position with same piece distribution and same result, is it worth a new issue ?). Indeed, it already exist !

I suggest making the button clearer. It's right next to the flip horizontally and vertically buttons and at the icon, I assumed it was some flipping board too.

If the button was located right next to the white to move/black to move buttons, it would be much more intuitive and I would have found out much earlier about it !

**Comment by niklasf** [comment]
Mhh ... yes, good idea. Done. Might require clearing the cache.
